export const cars = [
	{
		id: 'tcr-001',
		name: 'T-Cross',
		year: '2023',
		price: '₦15,000,000',
		description: '4.0 D5 PowerPulse Momentum with excellent fuel economy.',
		image: '/featured-car.png',
		specs: [
			{ text: '15 Miles', icon: '/speed-icon.png' },
			{ text: 'Petrol', icon: '/petrol-icon.png' },
			{ text: 'CVT', icon: '/cvt-icon.png' },
		],
	},
	{
		id: 'tcr-002',
		name: 'T-Cross',
		year: '2023',
		price: '₦15,000,000',
		description: '4.0 D5 PowerPulse Momentum with excellent fuel economy.',
		image: '/featured-car.png',
		specs: [
			{ text: '15 Miles', icon: '/speed-icon.png' },
			{ text: 'Petrol', icon: '/petrol-icon.png' },
			{ text: 'CVT', icon: '/cvt-icon.png' },
		],
	},
	{
		id: 'tcr-003',
		name: 'T-Cross',
		year: '2023',
		price: '₦15,000,000',
		description: '4.0 D5 PowerPulse Momentum with excellent fuel economy.',
		image: '/featured-car.png',
		specs: [
			{ text: '15 Miles', icon: '/speed-icon.png' },
			{ text: 'Petrol', icon: '/petrol-icon.png' },
			{ text: 'CVT', icon: '/cvt-icon.png' },
		],
	},
	{
		id: 'tcr-004',
		name: 'T-Cross',
		year: '2023',
		price: '₦15,000,000',
		description: '4.0 D5 PowerPulse Momentum with excellent fuel economy.',
		image: '/featured-car.png',
		specs: [
			{ text: '15 Miles', icon: '/speed-icon.png' },
			{ text: 'Petrol', icon: '/petrol-icon.png' },
			{ text: 'CVT', icon: '/cvt-icon.png' },
		],
	},
	{
		id: 'tcr-005',
		name: 'T-Cross',
		year: '2023',
		price: '₦15,000,000',
		description: '4.0 D5 PowerPulse Momentum with excellent fuel economy.',
		image: '/featured-car.png',
		specs: [
			{ text: '15 Miles', icon: '/speed-icon.png' },
			{ text: 'Petrol', icon: '/petrol-icon.png' },
			{ text: 'CVT', icon: '/cvt-icon.png' },
		],
	},
	{
		id: 'tcr-006',
		name: 'T-Cross',
		year: '2023',
		price: '₦15,000,000',
		description: '4.0 D5 PowerPulse Momentum with excellent fuel economy.',
		image: '/featured-car.png',
		specs: [
			{ text: '15 Miles', icon: '/speed-icon.png' },
			{ text: 'Petrol', icon: '/petrol-icon.png' },
			{ text: 'CVT', icon: '/cvt-icon.png' },
		],
	},
	{
		id: 'tcr-007',
		name: 'T-Cross',
		year: '2023',
		price: '₦15,000,000',
		description: '4.0 D5 PowerPulse Momentum with excellent fuel economy.',
		image: '/featured-car.png',
		specs: [
			{ text: '15 Miles', icon: '/speed-icon.png' },
			{ text: 'Petrol', icon: '/petrol-icon.png' },
			{ text: 'CVT', icon: '/cvt-icon.png' },
		],
	},
	// Add more unique car objects here
];
