export const cars = [
	{
		id: 'tcr-001',
		name: 'T-Cross',
		category: 'SUV',
		year: '2023',
		price: '₦15,000,000',
		description: '4.0 D5 PowerPulse Momentum with excellent fuel economy.',
		image: '/featured-car.png',
		specs: [
			{ text: '15 Miles', icon: '/speed-icon.png' },
			{ text: 'Petrol', icon: '/petrol-icon.png' },
			{ text: 'CVT', icon: '/cvt-icon.png' },
		],
	},
	{
		id: 'hcn-002',
		name: 'Honda Civic',
		category: 'Sedan',
		year: '2022',
		price: '₦9,500,000',
		description: 'Reliable compact sedan with great handling and fuel economy.',
		image: '/featured-car.png',
		specs: [
			{ text: '20 Miles', icon: '/speed-icon.png' },
			{ text: 'Petrol', icon: '/petrol-icon.png' },
			{ text: 'Manual', icon: '/cvt-icon.png' },
		],
	},
	{
		id: 'frd-003',
		name: 'Ford F-150',
		category: 'Truck',
		year: '2021',
		price: '₦20,000,000',
		description: 'Top-performing pickup with massive towing capacity.',
		image: '/featured-car.png',
		specs: [
			{ text: '12 Miles', icon: '/speed-icon.png' },
			{ text: 'Diesel', icon: '/petrol-icon.png' },
			{ text: 'Automatic', icon: '/cvt-icon.png' },
		],
	},
	{
		id: 'bmw-004',
		name: 'BMW 3 Series',
		category: 'Sedan',
		year: '2023',
		price: '₦25,000,000',
		description: 'Luxury sedan with powerful performance and sleek design.',
		image: '/featured-car.png',
		specs: [
			{ text: '18 Miles', icon: '/speed-icon.png' },
			{ text: 'Petrol', icon: '/petrol-icon.png' },
			{ text: 'Automatic', icon: '/cvt-icon.png' },
		],
	},
	{
		id: 'vwg-005',
		name: 'Volkswagen Golf',
		category: 'Hatchback',
		year: '2022',
		price: '₦11,000,000',
		description: 'Fun and practical hatchback with modern tech features.',
		image: '/featured-car.png',
		specs: [
			{ text: '22 Miles', icon: '/speed-icon.png' },
			{ text: 'Petrol', icon: '/petrol-icon.png' },
			{ text: 'Manual', icon: '/cvt-icon.png' },
		],
	},
	{
		id: 'rng-006',
		name: 'Range Rover Evoque',
		category: 'SUV',
		year: '2023',
		price: '₦35,000,000',
		description: 'Stylish and compact SUV with luxury features.',
		image: '/featured-car.png',
		specs: [
			{ text: '14 Miles', icon: '/speed-icon.png' },
			{ text: 'Petrol', icon: '/petrol-icon.png' },
			{ text: 'Automatic', icon: '/cvt-icon.png' },
		],
	},
	{
		id: 'tes-007',
		name: 'Tesla Model 3',
		category: 'Sedan',
		year: '2023',
		price: '₦30,000,000',
		description: 'Electric sedan with impressive range and autopilot features.',
		image: '/featured-car.png',
		specs: [
			{ text: 'Electric', icon: '/speed-icon.png' },
			{ text: 'EV', icon: '/petrol-icon.png' },
			{ text: 'Single Speed', icon: '/cvt-icon.png' },
		],
	},
];
